<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FinancialTransactionService.Presentation</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FinancialTransactionService.Application\FinancialTransactionService.Application.csproj"/>
        <ProjectReference Include="..\FinancialTransactionService.Infrastructure\FinancialTransactionService.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1"/>
    </ItemGroup>

</Project>
