<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>FinancialTransactionService.Infrastructure</RootNamespace>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FinancialTransactionService.Application\FinancialTransactionService.Application.csproj" />
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    </ItemGroup>
    
</Project>
